name: Check TwitchLib.Api PR Build Status

on:
  pull_request:
    branches: [ dev, master ]

jobs:
  check-buildstatus:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build TwitchLib.Api
      run: dotnet build --no-restore
